"""search and filter indexes on cases and documents

Revision ID: 35968b0ff2b2
Revises: a1b2c3d4e5f6
Create Date: 2026-09-09 23:10:11.224785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35968b0ff2b2'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_cases_title', 'cases', ['title'], unique=False)
    op.create_index('ix_documents_archived_at', 'documents', ['archived_at'], unique=False)
    op.create_index('ix_documents_folder_type', 'documents', ['folder_type'], unique=False)
    op.create_index('ix_documents_original_filename', 'documents', ['original_filename'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_original_filename', table_name='documents')
    op.drop_index('ix_documents_folder_type', table_name='documents')
    op.drop_index('ix_documents_archived_at', table_name='documents')
    op.drop_index('ix_cases_title', table_name='cases')
    # ### end Alembic commands ###
